// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ISW7FxJLh34rXZPn9ojt3DgXMoEY-l4',
    appId: '1:779880600850:web:d30a71979572d8ec84cfcb',
    messagingSenderId: '779880600850',
    projectId: 'hugsand-heart-u86wap',
    authDomain: 'hugsand-heart-u86wap.firebaseapp.com',
    storageBucket: 'hugsand-heart-u86wap.firebasestorage.app',
    measurementId: 'G-7DQFWG37P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6388Z_ToQ5DW2-CAZS-j8rtDox_pu5dY',
    appId: '1:779880600850:android:dfe73752a2b390de84cfcb',
    messagingSenderId: '779880600850',
    projectId: 'hugsand-heart-u86wap',
    storageBucket: 'hugsand-heart-u86wap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUNM7nAk9gDS6nBARWl5r61K2IxIZs6SI',
    appId: '1:779880600850:ios:266956591ab9660c84cfcb',
    messagingSenderId: '779880600850',
    projectId: 'hugsand-heart-u86wap',
    storageBucket: 'hugsand-heart-u86wap.firebasestorage.app',
    iosBundleId: 'com.example.lovingBrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUNM7nAk9gDS6nBARWl5r61K2IxIZs6SI',
    appId: '1:779880600850:ios:266956591ab9660c84cfcb',
    messagingSenderId: '779880600850',
    projectId: 'hugsand-heart-u86wap',
    storageBucket: 'hugsand-heart-u86wap.firebasestorage.app',
    iosBundleId: 'com.example.lovingBrain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6ISW7FxJLh34rXZPn9ojt3DgXMoEY-l4',
    appId: '1:779880600850:web:91b7e7c697161e6c84cfcb',
    messagingSenderId: '779880600850',
    projectId: 'hugsand-heart-u86wap',
    authDomain: 'hugsand-heart-u86wap.firebaseapp.com',
    storageBucket: 'hugsand-heart-u86wap.firebasestorage.app',
    measurementId: 'G-BXC73W7HFW',
  );
}
